### ISSUE TITLE
non sudo error handler disappeared in recent version

### ISSUE THREAD

**Issue by greg-pendlebury** [nla/jvmctl#5]
```
[gpendleb@alfarin ~]$ jvmctl newspapers-browse restart
Traceback (most recent call last):
  File "/opt/bin/jvmctl", line 911, in <module>
    if __name__ == '__main__': main()
  File "/opt/bin/jvmctl", line 904, in main
    sys.exit(commands[cmd](Node(node), *args) or 0)
  File "/opt/bin/jvmctl", line 503, in restart
    node.autoregister()
  File "/opt/bin/jvmctl", line 441, in autoregister
    systemd_register(self)
  File "/opt/bin/jvmctl", line 807, in systemd_register
    with os.fdopen(os.open(env_file, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0600                                                                                                                      ), 'w') as f:
OSError: [Errno 13] Permission denied: '/var/cache/jvmctl/base/newspapers-browse                                                                                                                      /environment'
[gpendleb@alfarin ~]$ sudo jvmctl newspapers-browse restart
```

**Comment by anniecollins-nla** [comment]
https://github.com/nla/jvmctl/commit/109e7c854f539a5522ba8067933429d3ed9ff020
